
services:

  # -------------------------------
  # PostgreSQL 16
  # -------------------------------
  db-service:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: gptdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - gptdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gptdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # -------------------------------
  # PGAdmin
  # -------------------------------
  pgadmin-service:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8080:80"
    depends_on:
      db-service:
        condition: service_healthy
    restart: always

  # -------------------------------
  # Backend FastAPI
  # -------------------------------
  backend-service:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/gptdb
    depends_on:
      db-service:
        condition: service_healthy
    restart: always

# -------------------------------
# Volume persistant
# -------------------------------
volumes:
  gptdata:
